import Head from 'next/head';
import Header from '@/components/Header/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ratebird | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <main>
        <Header />
      </main>
    </>
  );
}
